services:
  knowledge-mapping:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./conf.json:/app/conf.json
      - /home/ynsjk/git/priv_The-Knowledge:/the-knowledge
      - /home/ynsjk/.ssh/github_key:/tmp/github_key:ro

    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Zurich
      - GIT_SSH_COMMAND=ssh -i /run/secrets/github_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new
