services:
  knowledge-mapping:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./conf.json:/app/conf.json
      - C:\Users\yanis\Desktop\Git\The-Knowledge:/the-knowledge
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Zurich
