services:
  knowledge-mapping:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./conf.json:/app/conf.json
      - /home/ynsjk/git/priv_The-Knowledge/02_DOCS:/docs
      - /home/ynsjk/git/priv_The-Knowledge/README.md:/todo/README.md
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Zurich
